apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: api-gateway-hpa
    labels:
        app: api-gateway
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: api-gateway
    minReplicas: 2
    maxReplicas: 6
    metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
        - type: Resource
          resource:
              name: memory
              target:
                type: Utilization
                averageUtilization: 50
