services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}", "-d", "${DB_NAME}"]
      interval: 20s
      timeout: 10s
      retries: 5

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${MQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${MQ_PASSWORD}
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 20s
      timeout: 10s
      retries: 5

  user-service:
    image: jakepel03/event4you-user-service:latest
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres
      DB_PORT: 5432
      JWT_SECRET: ${JWT_SECRET}
      API_GATEWAY_HOST: localhost
      API_GATEWAY_PORT: 8080
      NOTIFICATION_SERVICE_HOST: notification-service
      NOTIFICATION_SERVICE_PORT: 8086
      MQ_USERNAME: ${MQ_USERNAME}
      MQ_PASSWORD: ${MQ_PASSWORD}
      MQ_HOST: rabbitmq
    depends_on:
      - rabbitmq
      - postgres

  notification-service:
    image: jakepel03/event4you-notification-service:latest
    container_name: notification-service
    ports:
      - "8086:8086"
      - "15672:15672"
    environment:
      MQ_USERNAME: ${MQ_USERNAME}
      MQ_PASSWORD: ${MQ_PASSWORD}
      MQ_HOST: rabbitmq
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      SPRING_MAIL_NAME: ${SPRING_MAIL_NAME}
    depends_on:
      - rabbitmq

  venue-service:
    image: jakepel03/event4you-venue-service:latest
    container_name: venue-service
    ports:
      - "8084:8084"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres
      DB_PORT: 5432
      MQ_USERNAME: ${MQ_USERNAME}
      MQ_PASSWORD: ${MQ_PASSWORD}
      MQ_HOST: rabbitmq
    depends_on:
      - rabbitmq
      - postgres

  payment-service:
    image: jakepel03/event4you-payment-service:latest
    container_name: payment-service
    ports:
      - "8082:8082"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres
      DB_PORT: 5432
      MQ_USERNAME: ${MQ_USERNAME}
      MQ_PASSWORD: ${MQ_PASSWORD}
      MQ_HOST: rabbitmq
      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
      PAYPAL_CLIENT_SECRET: ${PAYPAL_CLIENT_SECRET}
      PAYPAL_MODE: ${PAYPAL_MODE}
      API_GATEWAY_HOST: localhost
      API_GATEWAY_PORT: 8080
    depends_on:
      - rabbitmq
      - postgres

  event-service:
    image: jakepel03/event4you-event-service:latest
    container_name: event-service
    ports:
      - "8083:8083"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres
      - rabbitmq

  api-gateway:
    image: jakepel03/event4you-api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      USER_SERVICE_HOST: user-service
      USER_SERVICE_PORT: 8081
      PAYMENT_SERVICE_HOST: payment-service
      PAYMENT_SERVICE_PORT: 8082
      EVENT_SERVICE_HOST: event-service
      EVENT_SERVICE_PORT: 8083
      VENUE_SERVICE_HOST: venue-service
      VENUE_SERVICE_PORT: 8084
      GUEST_SERVICE_HOST: guest-service
      GUEST_SERVICE_PORT: 8085
      NOTIFICATION_SERVICE_HOST: notification-service
      NOTIFICATION_SERVICE_PORT: 8086
    depends_on:
      - user-service
      - payment-service
      - event-service
      - venue-service
      - notification-service

volumes:
  postgres_data:
