apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
    replicas: 1
    selector:
      matchLabels:
        app: user-service
    template:
      metadata:
        labels:
          app: user-service
      spec:
        containers:
          - name: user-service
            image: jakepel03/event4you-user-service:latest
            imagePullPolicy: Always
            ports:
                - containerPort: 8081
            livenessProbe:
              httpGet:
                port: 8081
                path: /users/health
              initialDelaySeconds: 10
              periodSeconds: 10
              failureThreshold: 3
              successThreshold: 1
            readinessProbe:
              httpGet:
                port: 8081
                path: /users/health
              initialDelaySeconds: 20
              periodSeconds: 10
              failureThreshold: 3
              successThreshold: 1
            envFrom:
              - configMapRef:
                  name: service-config
              - secretRef:
                  name: services-secrets



