apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
      app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: jakepel03/event4you-notification-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
          livenessProbe:
            httpGet:
              port: 8086
              path: /notifications/health
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              port: 8086
              path: /notifications/health
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          envFrom:
              - configMapRef:
                  name: service-config
              - secretRef:
                  name: services-secrets