apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
      app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: jakepel03/event4you-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
              - configMapRef:
                  name: service-config
              - secretRef:
                  name: services-secrets
---
