apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: jakepel03/event4you-payment-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          livenessProbe:
            httpGet:
              port: 8082
              path: /payments/health
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              port: 8082
              path: /payments/health
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          envFrom:
            - configMapRef:
                name: service-config
            - secretRef:
                name: services-secrets

