apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: payment-service-hpa
    labels:
        app: payment-service
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: payment-service
    minReplicas: 2
    maxReplicas: 4
    metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
        - type: Resource
          resource:
              name: memory
              target:
                type: Utilization
                averageUtilization: 50
